language: go
go: 1.14
dist: bionic
services:
  - xvfb
env:
  - NODE_VERSION="16.1" GO111MODULE=on
before_install:
  - nvm install $NODE_VERSION
install:
  - ./ci/ci.sh install ${TRAVIS_BRANCH}
before_script:
  - export DISPLAY=:99.0;
script:
  - ./ci/ci.sh build ${TRAVIS_BRANCH}
  - ./ci/ci.sh test ${TRAVIS_BRANCH}
  - ./ci/ci.sh prepublish ${TRAVIS_BRANCH}
deploy:
  - provider: releases
    api-key: $GH_TOKEN
    file: 
      - yodk-win.zip
      - yodk-linux.zip
      - yodk-darwin.zip
      - vscode-yolol.vsix
    skip_cleanup: true
    edge: true
    release_notes_file: "CHANGELOG.md"
    on:
      tags: true
  - provider: script
    script: ./ci/ci.sh publish ${TRAVIS_TAG} ${VSCODE_MARKETPLACE_TOKEN}
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GH_TOKEN
    on:
      branch: master