language: go
go: 1.14
dist: bionic
services:
  - xvfb
env:
  - NODE_VERSION="16.1" GO111MODULE=on
before_install:
  - nvm install $NODE_VERSION
install:
  - make setup
before_script:
  - export DISPLAY=:99.0;
script:
  - make all VERSION=${TRAVIS_BRANCH}
  - ls -al
deploy:
  - provider: releases
    api-key: $GH_TOKEN
    file: 
      - yodk-win.zip
      - yodk-linux.zip
      - yodk-darwin.zip
      - vscode-yolol.vsix
    skip_cleanup: true
    edge: true
    release_notes_file: "CHANGELOG.md"
    on:
      tags: true
  - provider: script
    script: make publish-vsix VERSION=${TRAVIS_TAG} TOKEN=${VSCODE_MARKETPLACE_TOKEN}
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GH_TOKEN
    on:
      branch: master