language: go
go: 1.14
dist: bionic
services:
  - xvfb
env:
  - NODE_VERSION="16.1" GO111MODULE=on

before_install:
  - nvm install $NODE_VERSION
install:
  - go mod download
  - cd vscode-yolol && npm install && npm install -g vsce && cd ..
before_script:
  - export DISPLAY=:99.0;
script:
  - go test ./...
  - go build -ldflags "-X github.com/dbaumgarten/yodk/cmd.YodkVersion=${TRAVIS_BRANCH}"
  - ./yodk version
  - GOOS=windows go build -ldflags "-X github.com/dbaumgarten/yodk/cmd.YodkVersion=${TRAVIS_BRANCH}"
  - GOOS=darwin go build -o yodk-darwin -ldflags "-X github.com/dbaumgarten/yodk/cmd.YodkVersion=${TRAVIS_BRANCH}"
  - cd vscode-yolol
  - npm run vscode:prepublish
  - npm test --silent
  - cd ..
  - ./build-changelog.sh
before_deploy:
  - cp CHANGELOG.md vscode-yolol/
  - cd vscode-yolol
  - npm version --no-git-tag-version $(echo ${TRAVIS_TAG} | tr -d v) --allow-same-version
  - vsce package
  - cp *.vsix ../vscode-yolol.vsix
  - cd ..
  - zip yodk-win.zip yodk.exe
  - zip yodk-linux.zip yodk
  - zip yodk-darwin.zip yodk-darwin
  - ./build-docs.sh
deploy:
  - provider: releases
    api-key: $GH_TOKEN
    file: 
      - yodk-win.zip
      - yodk-linux.zip
      - yodk-darwin.zip
      - vscode-yolol.vsix
    skip_cleanup: true
    edge: true
    release_notes_file: "CHANGELOG.md"
    on:
      tags: true
  - provider: script
    script: vsce publish --packagePath vscode-yolol.vsix -p ${VSCODE_MARKETPLACE_TOKEN}
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GH_TOKEN
    on:
      branch: master